### PR TITLE
Return response

### PR DESCRIPTION
**Pull request by erik-ropez**
Return response so that it can be parsed in event listener.

### CODE REVIEW

**Comment by erik-ropez** [comment]
@chrisbjr Hello! What's wrong with StyleCI? It tells there is something to fix but doesn't say what exactly.
image

**Comment by chrisbjr** [comment]
Hi @erik-ropez sorry for the late response.

StyleCI wants a new line before the `return` statement :)

**Comment by urukalo** [comment]
@erik-ropez is there any example how to catch response returned on this way? can You fix this StyleCI problem, please?

@chrisbjr is there any other option to catch response from firebase (on example:  to delete old/invalid device tokens), or this pull req is only one?

**Comment by chrisbjr** [comment]
Hi @urukalo I'm thinking for this case, I'll just fire off an event which you can attach listeners to. What do you think?

**Comment by erik-ropez** [comment]
@chrisbjr blank line added.

@urukalo you can use event listener for `Illuminate\Notifications\Events\NotificationSent`. Register it inside Laravel's `EventServiceProvider`. Event object has `response` property which contains response from FCM. This is what is added in this branch. You can parse it with some thing like `json_decode($event->response->getBody()->getContents())`.

**Comment by chrisbjr** [comment]
hi @erik-ropez cool, why did you delete the branch though?

**Comment by erik-ropez** [comment]
@chrisbjr Was doing some cleanup and removed by mistake. Restored now.

**Comment by urukalo** [comment]
uh.. what mess is made here..

**Pull request closed without merging**
